FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
RUN chmod -R a+x node_modules/.bin || true
COPY . .
ARG VITE_REACT_APP_SERVER_URL
ENV VITE_REACT_APP_SERVER_URL=${VITE_REACT_APP_SERVER_URL}
ENV NODE_ENV=production
RUN node ./node_modules/vite/bin/vite.js build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

