namespace BookStack.Features.Identity.Web;

using Common;
using Identity.Shared;
using Infrastructure.Extensions;
using Microsoft.AspNetCore.Mvc;
using Models;
using Service;
using Service.Models;

/// <summary>
/// Exposes authentication and credential-recovery endpoints.
/// </summary>
/// <remarks>
/// This controller maps web models to service models and delegates business rules to
/// <see cref="IIdentityService"/>.
/// </remarks>
public class IdentityController(IIdentityService service) : ApiController
{
    /// <summary>
    /// Registers a new user account and returns a JWT on success.
    /// </summary>
    /// <param name="webModel">Registration payload, including optional profile image upload.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    /// <returns>
    /// `200 OK` with a JWT token when registration succeeds, or `400 Bad Request` when validation or
    /// business rules fail.
    /// </returns>
    /// <remarks>
    /// The request is bound from form data because registration supports file upload.
    /// </remarks>
    [HttpPost(ApiRoutes.RegisterRoute)]
    public async Task<ActionResult<JwtTokenServiceModel>> Register(
        [FromForm] RegisterWebModel webModel,
        CancellationToken cancellationToken = default)
    {
        var serviceModel = webModel.ToRegisterServiceModel();
        var result = await service.Register(
            serviceModel,
            cancellationToken);

        return this.OkOrBadRequest(
            result,
            static token => new JwtTokenServiceModel(token));
    }

    /// <summary>
    /// Authenticates a user by username or email and returns a JWT on success.
    /// </summary>
    /// <param name="webModel">Login credentials and remember-me preference.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    /// <returns>
    /// `200 OK` with a JWT token when credentials are valid, or `400 Bad Request` for invalid login attempts.
    /// </returns>
    [HttpPost(ApiRoutes.LoginRoute)]
    public async Task<ActionResult<JwtTokenServiceModel>> Login(
        LoginWebModel webModel,
        CancellationToken cancellationToken = default)
    {
        var serviceModel = webModel.ToLoginServiceModel();
        var result = await service.Login(
            serviceModel,
            cancellationToken);

        return this.OkOrBadRequest(
            result,
            static token => new JwtTokenServiceModel(token));
    }

    /// <summary>
    /// Requests a password reset email for the supplied address.
    /// </summary>
    /// <param name="webModel">Forgot-password request payload.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    /// <returns>
    /// `200 OK` with a generic message on accepted requests, or `400 Bad Request` when request validation fails.
    /// </returns>
    [HttpPost(ApiRoutes.ForgotPasswordRoute)]
    public async Task<ActionResult<MessageServiceModel>> ForgotPassword(
       ForgotPasswordWebModel webModel,
       CancellationToken cancellationToken = default)
    {
        var serviceModel = webModel.ToForgotPasswordServiceModel();
        var result = await service.ForgotPassword(
            serviceModel,
            cancellationToken);

        return this.OkOrBadRequest(
            result,
            static message => new MessageServiceModel(message));
    }

    /// <summary>
    /// Resets a user's password with a reset token generated by the forgot-password flow.
    /// </summary>
    /// <param name="webModel">Reset password payload containing email, token, and new password.</param>
    /// <returns>
    /// `200 OK` with a success message when the reset completes, or `400 Bad Request` when the token or data is invalid.
    /// </returns>
    [HttpPost(ApiRoutes.ResetPasswordRoute)]
    public async Task<ActionResult<MessageServiceModel>> ResetPassword(
        ResetPasswordWebModel webModel)
    {
        var serviceModel = webModel.ToResetPasswordServiceModel();
        var result = await service.ResetPassword(
            serviceModel);

        return this.OkOrBadRequest(
            result,
            static message => new MessageServiceModel(message));
    }
}
