namespace BookStack.Features.Identity.Service;

using Infrastructure.Services.Result;
using Infrastructure.Services.ServiceLifetimes;
using Models;

/// <summary>
/// Provides account authentication and credential-recovery operations.
/// </summary>
public interface IIdentityService : IScopedService
{
    /// <summary>
    /// Creates a new account and returns a JWT token for immediate authentication.
    /// </summary>
    /// <param name="model">Registration data, including optional profile image.</param>
    /// <param name="cancellationToken">Token used to cancel the operation.</param>
    /// <returns>
    /// A result containing a JWT when successful; otherwise a failure message describing the rejected registration.
    /// </returns>
    Task<ResultWith<string>> Register(
        RegisterServiceModel model,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Authenticates a user and returns a JWT token when credentials are valid.
    /// </summary>
    /// <param name="model">Credentials payload and remember-me preference.</param>
    /// <param name="cancellationToken">Token used to cancel the operation.</param>
    /// <returns>
    /// A result containing a JWT when successful; otherwise a failure message for invalid or locked accounts.
    /// </returns>
    Task<ResultWith<string>> Login(
        LoginServiceModel model,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Initiates password reset by sending a reset link when the account exists.
    /// </summary>
    /// <param name="model">Forgot-password request data.</param>
    /// <param name="cancellationToken">Token used to cancel the operation.</param>
    /// <returns>
    /// A generic success message regardless of account existence to avoid user enumeration.
    /// </returns>
    Task<ResultWith<string>> ForgotPassword(
        ForgotPasswordServiceModel model,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Resets a password using a reset token generated by <see cref="ForgotPassword"/>.
    /// </summary>
    /// <param name="model">Reset-password payload with email, token, and new password.</param>
    /// <returns>
    /// A success message when the password was changed; otherwise a failure message describing why the reset was rejected.
    /// </returns>
    Task<ResultWith<string>> ResetPassword(
        ResetPasswordServiceModel model);
}
